import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ShoppingListItem from '../components/ShoppingListItem'
import getShoppingItems from '../services/getShoppingItems'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.shoppingListItemContainer}>
        {getShoppingItems().map(item => (
          <ShoppingListItem
            key={item.id}
            title={item.title}
            description={item.description}
            price={item.price}
            thumbnailImg={item.thumbnailImg}
          />

        ))}
      </div>


    </div>
  )
}
