import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ShoppingListItem from '../components/ShoppingListItem'
import getShoppingItems from '../services/getShoppingItems'
import { useState } from 'react'
import FontSizeSelector from '../components/FontSizeSelector'

export default function Home() {
  const [fontSize, setFontSize] = useState(14)

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FontSizeSelector setFontSize={setFontSize} />

      <div className={styles.shoppingListItemContainer}>
        {getShoppingItems().map(item => (
          <ShoppingListItem
            titleFontSize={fontSize}
            key={item.id}
            title={item.title}
            description={item.description}
            price={item.price}
            thumbnailImg={item.thumbnailImg}
          />

        ))}
      </div>


    </div>
  )
}
