import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ShoppingListItem from '../components/ShoppingListItem'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ShoppingListItem
        title="Tourmaline & Eucalyptus Bar Soap"
        description="Recharge your skin with the super energizing power of finely crushed tourmaline powder blended with natural complexion."
        price="12.00"
        thumbnailImg="/images/test-soap-thumbnails/tourmaline-&-argan-oil-bar-soap.png"
      />

    </div>
  )
}
